version: "3.9"

volumes:
  influxdb_data: {}
  postgres_data: {}
  grafana_data: {}

networks:
  influx:
    name: influx-frontend
  postgres:
    external: false

services:
  influxdb:
    container_name: dsig-influx
    image: influxdb:${INFLUXDB_VERSION}
    networks:
      - influx
    ports:
      - 8086:8086
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/ping"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    restart: always
    env_file:
      - ./influxdb/influxdb.env
    volumes:
      - influxdb_data:/var/lib/influxdb2
      - ./influxdb/config.yml:/etc/influxdb2/config.yml

  telegraf:
    container_name: dsig-telegraf
    image: telegraf:${TELEGRAF_VERSION}
    profiles: ["telegraf"]
    networks:
      - influx
    ports:
      - 8125:8125/udp
    restart: always
    depends_on:
      - influxdb
    env_file:
      - ./telegraf/telegraf.env
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro

  postgres:
    container_name: dsig-postgres
    image: bitnami/postgresql:${POSTGRES_VERSION}
    profiles: ["grafana"]
    networks:
      - postgres
    restart: always
    env_file:
      - ./postgres/postgres.env
    volumes:
      - postgres_data:/bitnami/postgresql

  grafana:
    container_name: dsig-grafana
    image: grafana/grafana-enterprise:${GRAFANA_VERSION}
    profiles: ["grafana"]
    networks:
      - postgres
      - influx
    ports:
      - 3000:3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    restart: always
    depends_on:
      - postgres
      - influxdb
    env_file:
      - ./grafana/grafana.env
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/etc/dashboards

  # Other services
  mqtt:
  # docker run -it --rm --name mqtt-subscriber --network influx-frontend efrecon/mqtt-client sub -h mqtt -t "ngsi/#"
  # docker run -it --rm --name mqtt-publisher --network influx-frontend efrecon/mqtt-client pub -h mqtt -m '{"@context":"http://example.org","id":"urn:abc","temperature":23,"humidity":45.6}' -t "ngsi/ld"
    container_name: dsig-mosquitto
    image: eclipse-mosquitto #:1.6.15
    networks:
      - influx
    expose:
      - "1883"
      - "9001"
    ports:
      - "1883:1883" # localhost:1883
      - "9001:9001" # localhost:9001
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    healthcheck:
      test: ["CMD-SHELL", "curl", "-f", "http://localhost:1883" ]
      interval: 10s
      timeout: 10s
      retries: 6